### PR TITLE
Removing profile support

### PR DESCRIPTION
**Pull request by BigMacAdmin**
- Removed functions and references to local profiles

### CODE REVIEW

**Comment by natewalck** [comment]
LGTM, but I'll defer to @bartreardon as I'm not nearly as familiar with this code base.

shipit2

**Comment by bartreardon** [comment]
the deletions look good but seems you branched from development which has an unmerged change in it - if you can remove [outset/Outset.swift](https://github.com/macadmins/outset/pull/8#diff-dec3dbe303ca25300a8023d39b08600167f32a6dcf2436444787fb95d3a4b56b) from your commit as it's unrelated to removing the profile stuff.

**Review by bartreardon — APPROVED** [review]
Looks good 🙂

**Comment by natewalck** [comment]
This closes out #8

**Pull request merged**
